[package]
name = "kyuri"
version = "0.1.2"
edition = "2021"
description = "A very simple progress display library"
license = "MIT"
repository = "https://github.com/taoky/kyuri"

[dependencies]

[dev-dependencies]
nix = { version = "0.29.0", features = ["fs"] }
rand = "0.8"
